diary: tune query
treby/isucon5-exercise pull request #10
Opened 2017-10-14 10:23 UTC by treby

2017-10-14 10:30 UTC, kei-q commented
fail
20.8
{"success"=>20, "redirect"=>8, "failure"=>0, "error"=>0, "exception"=>0}
パス '/diary/entry/500354' へのレスポンスコード 403 が期待されていましたが 200 でした

2017-10-14 10:33 UTC, kei-q requested changes
ただしくうごきません

2017-10-14 10:45 UTC, treby commented
なおしました

2017-10-15 00:22 UTC, edwardkenfox approved these changes
lgtm

2020-09-14 14:36 UTC, closed without merging